### PR TITLE
intent weather added

### LINKED ISSUE #53: Add new Intent: Weather
`Weather Information`
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by gan3i**
kindly accept the PR. Closes #53

### CODE REVIEW

**Comment by swapagarwal** [comment]
Needs location entity.

**Comment by RohitRathore1** [comment]
@gan3i Needs location entity. Do the necessary changes and resolve the conflicts.

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@gan3i Tests are failing. 
https://travis-ci.org/github/the-vision/jarvis-core/builds/679101952

**Comment by gan3i** [comment]
Hi @TeAmP0is0N I tried running the solution in gitpot but I am getting bellow error while installing dependencies.
image
I did try with newer version on tensorflow still got the same error.

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@gan3i You are using version of tensorflow `tensorflow==2.1.0` but check our requirement file. We need `tensorflow==1.13.2`. So, I would suggest you to install `tensorflow==2.1.0`

**Comment by RohitRathore1** [comment]
Use ` pip install "tensorflow>=1.13.2"`

**Comment by gan3i** [comment]
I get the similar error with 1.13.2, and I am trying this in gitpod, I get the similar error in local as well.
image

**Comment by gan3i** [comment]
image

**Comment by swapagarwal** [comment]
Closing due to inactivity.

**Pull request closed without merging**
