### PR TITLE
Intent classification using Ludwig

### PR DESCRIPTION
**Pull request by SubhradeepSS**
Issues handled: #58  #57

### CODE REVIEW

**Comment by SubhradeepSS** [comment]
@TeAmP0is0N This is the [folder](https://github.com/SubhradeepSS/jarvis-core/tree/master/Automated%20Intent%20classification) I added in which the notebook as well as the dataset used is present.
Please review those and let me know.

**Comment by SubhradeepSS** [comment]
> 
> 
> @TeAmP0is0N This is the [folder](https://github.com/SubhradeepSS/jarvis-core/tree/master/Automated%20Intent%20classification) I added in which the notebook as well as the dataset used is present.
> Please review those and let me know.

@TeAmP0is0N Did u check?

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@SubhradeepSS Take more datasets like this and work on those datasets.

**Comment by SubhradeepSS** [comment]
> 
> 
> @SubhradeepSS Take more datasets like this and work on those datasets.

Will the PR be merged after working on all datasets?

**Comment by RohitRathore1** [comment]
Yes, your PR will merge.

**Comment by SubhradeepSS** [comment]
> 
> 
> Yes, your PR will merge.
@TeAmP0is0N 
Upto how many datasets do I need to work on?Shouldn't the PRs be separately merged for every dataset as this will count towards gssoc score?Please correct me if I am wrong

**Comment by RohitRathore1** [comment]
@SubhradeepSS No, you should not create diff PR. You can add upto total 5 datasets in a PR.

**Comment by RohitRathore1** [comment]
> Issues handled: #58 #57

You are handling only issue no #58 right now. So mention only #58.

**Comment by SubhradeepSS** [comment]
> 
> 
> > Issues handled: #58 #57
> 
> You are handling only issue no #58 right now. So mention only #58.

@TeAmP0is0N Did u check my notebook?I have also worked on #57

**Comment by RohitRathore1** [comment]
@SubhradeepSS yes, I checked your PR. in related to issue no #57 there will be more issue. #57 is the base for `intent classification`. For now you are working only on Datasets.

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
Needs more work to integrate with the bot. Can't be merged as-is.

**Pull request closed without merging**
