### PR TITLE
Intent: bye added

### LINKED ISSUE #4: Add new intent: bye
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by hritikksingh**
Fixes #4

### CODE REVIEW

**Comment by swapagarwal** [comment]
@hritikpapa You can test locally before pushing as well. 😇

**Comment by hritikksingh** [comment]
> @hritikpapa You can test locally before pushing as well. innocent

@swapagarwal I am really sorry, now it is working fine.

**Review by sgpritam — APPROVED** [review]

**Comment by hritikksingh** [comment]
@swapagarwal @sgpritam @TeAmP0is0N  is it good for merging it to the master?

**Comment by swapagarwal** [comment]
Thanks @hritikpapa! 👍

**Pull request merged**
