### PR TITLE
added new intent for help

### LINKED ISSUE #8: Add new intent: help
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by hritikksingh**
**Fixes #8**
@TeAmP0is0N @swapagarwal please review my PR.

### CODE REVIEW

**Review by RohitRathore1 — APPROVED** [review]

**Comment by hritikksingh** [comment]
@TeAmP0is0N is the changes made are good?
If yes, then why not merge it. :)

**Comment by tanisha03** [comment]
@hritikpapa we will merge it soon

**Comment by swapagarwal** [comment]
Needs rebase.

**Comment by hritikksingh** [comment]
@swapagarwal what is rebase, help with that, I am a beginner.

**Comment by hritikksingh** [comment]
Some one please help me on this.

**Comment by RohitRathore1** [comment]
@hritikpapa Your code has some conflicts. You have to solve these conflicts.

**Comment by hritikksingh** [comment]
> @hritikpapa Your code has some conflicts. You have to solve these conflicts.

Okay I will try doing that.

**Comment by RohitRathore1** [comment]
@hritikpapa See this article and ping me personally on slack.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by hritikksingh** [comment]
@TeAmP0is0N  it's not resolving, I have tried but it's simply showing everything is up to date.

**Comment by swapagarwal** [comment]
Merged in https://github.com/the-vision/jarvis-core/commit/98fb5ebb640306a9e193cde6dd3d456c1f532257

**Pull request closed without merging**
