### PR TITLE
Intent: fact added

### LINKED ISSUE #6: Add new intent: fact
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by sunchit17**
This resolves #6

### CODE REVIEW

**Comment by RohitRathore1** [comment]
hey @sunchit17 please resolve conflicts of this PR.

**Comment by sunchit17** [comment]
@TeAmP0is0N Resolved conflicts

**Comment by swapagarwal** [comment]
Thanks @sunchit17! 👍

**Comment by sunchit17** [comment]
@swapagarwal Happy to contribute 😄

**Pull request merged**
