### PR TITLE
Intent for travel

### LINKED ISSUE #14: Add new intent: travel
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by sunchit17**
resolves #14 
Added travel intent

### CODE REVIEW

**Comment by sunchit17** [comment]
Please review the changes for the issue referenced #14 
Closes #14

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
The destination should be extracted as an entity.

**Comment by sunchit17** [comment]
@TeAmP0is0N how do I add the destination entity?

**Comment by sunchit17** [comment]
@swapagarwal @TeAmP0is0N Request review and help for destination extraction in test.py

**Review by RohitRathore1 — APPROVED** [review]

**Pull request merged**
