### PR TITLE
Added new intent: currency

### LINKED ISSUE #60: Add new intent: currency
Currency intent must be added for use in `jarvis-telegram`

@swapagarwal @TeAmP0is0N Please assign me the issue.

### PR DESCRIPTION
**Pull request by adityabisoi**
Closes #60 

Currency intent added, with tests.

@TeAmP0is0N Please review this. Let me know if any additional changes are needed.

### CODE REVIEW

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
Tests are failing: https://travis-ci.org/github/the-vision/jarvis-core/builds/670201577

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@adityabisoi Tests are failing: https://travis-ci.org/github/the-vision/jarvis-core/builds/670201577 . Do the necessary changes and before commiting changes, check it to your local development that it is working or not.

**Comment by adityabisoi** [comment]
@swapagarwal @TeAmP0is0N I have made the changes, the tests are passing now. Please review.

**Comment by swapagarwal** [comment]
@adityabisoi Please add a test case that is not present in training data. I just found out that `define space` works in the dictionary module but `define server` doesn't.

**Comment by adityabisoi** [comment]
@swapagarwal Can you please tell me how did you test this?

**Comment by swapagarwal** [comment]
Frankly, I didn't catch it in the PR stage. 😅
After merging, I was playing with the bot on Telegram and there I found some queries to be not working.

**Review by RohitRathore1 — APPROVED** [review]

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@adityabisoi Resolve Conflicts!

**Pull request merged**
