### PR TITLE
Intent: Translator Added

### PR DESCRIPTION
**Pull request by HarshCasper**
Issue Reference: https://github.com/the-vision/jarvis-core/issues/25

Files updated: 

data/nlu.md
test.py

Kindly look into it and please let me know if any changes are needed.

### CODE REVIEW

**Comment by RohitRathore1** [comment]
Hey @HarshCasper please resolve conflicts of your PR.

**Comment by HarshCasper** [comment]
I have resolved all the conflicts with PR. Kindly look into it @TeAmP0is0N

**Review by RohitRathore1 — APPROVED** [review]

**Comment by HarshCasper** [comment]
Can you please merge this commit @swapagarwal

**Comment by RohitRathore1** [comment]
@HarshCasper Resolve your conflicts.

**Comment by swapagarwal** [comment]
The text should be extracted as an entity.

**Comment by adityabisoi** [comment]
@HarshCasper Can you please update the PR with required changes? A module in another repository depends upon this intent.

**Comment by HarshCasper** [comment]
@adityabisoi I will update the changes by tomorrow morning for sure.

**Comment by HarshCasper** [comment]
I have made the necessary changes. But I could not still understand what "text should be extracted as an entity".

Please let me know about this @swapagarwal so that I can make the final changes and push it. I have updated the merge conflicts.

**Comment by swapagarwal** [comment]
An intent is something your end-user wants to perform, e.g. Ask about the weather, Set an alarm on their smartwatch, Open the garage door, Say hello to their robot, etc.

If your user says Set the alarm at 7am, it’s not enough to know that it’s a set_alarm intent: you also need to capture the exact date and time at which the alarm should be set (“7 am”, presumably tomorrow). This extra information is called an entity.

So in this module, translate is the intent while the text you want to get translated will be an entity. See the music module for an example. @HarshCasper

**Comment by HarshCasper** [comment]
I have added the changes. Kindly review it and let me know if something is wrong.

**Comment by adityabisoi** [comment]
@HarshCasper The entity `value` should be the `text` to be translated.

**Comment by HarshCasper** [comment]
I have updated the change. Kindly check it.

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@HarshCasper Please resolve the conflicts.

**Pull request merged**
