### PR TITLE
Added new intent:Unit conversion

### PR DESCRIPTION
**Pull request by csharp489**
PR #71  
I have added new intent Unit Conversion. Please check it and merge it as well because you @TeAmP0is0N have not given score on my profile page of GSSoC20 . I hope u understand.

Please check it @TeAmP0is0N .

### CODE REVIEW

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
Tests are failing: https://travis-ci.org/github/the-vision/jarvis-core/builds/677180519

**Comment by RohitRathore1** [comment]
@csharp489 tests are failing. Do the necessary changes and commit your changes after checking it to your local development.

**Comment by RohitRathore1** [comment]
> @csharp489 tests are failing. Do the necessary changes and commit your changes after checking it to your local development.

@csharp489 Are you working on it?

**Comment by swapagarwal** [comment]
Closing due to inactivity.

**Pull request closed without merging**
