### PR TITLE
Added new intent: dictionary

### LINKED ISSUE #54: Add new intent: dictionary
https://github.com/the-vision/jarvis-core/wiki

### PR DESCRIPTION
**Pull request by adityabisoi**
Closes #54 

Dictionary intent added with its tests.

@TeAmP0is0N Please review and suggest changes if any.

### CODE REVIEW

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
@adityabisoi Please see if tests are passing on your local machine. You would have to extract the word as an entity, see music module for reference.

**Comment by TeAmP0is0N** [comment]
@adityabisoi Please see if tests are passing on your local machine. You would have to extract the word as an entity, see music module for reference and also resolve your conflicts.

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
@adityabisoi Please see if tests are passing on your local machine. You would have to extract the word as an entity, see music module for reference and also resolve your conflicts.

**Comment by adityabisoi** [comment]
@swapagarwal @TeAmP0is0N The tests are passing now. Please review.

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
Thanks @adityabisoi! 👍

**Pull request merged**
