### PR TITLE
Update nlu.md

### PR DESCRIPTION
**Pull request by tanvikapoor29**

### CODE REVIEW

**Comment by tanvikapoor29** [comment]
#40

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
Commit changes in `test.py` file also

**Comment by RohitRathore1** [comment]
@tanvikapoor29 Are you working on it?

**Comment by tanvikapoor29** [comment]
yes, i am working on it.

**Comment by RohitRathore1** [comment]
@tanvikapoor29 Are you working on it?

**Pull request merged**
